### ISSUE TITLE
Can this work with Angular framework?

### ISSUE THREAD

**Issue by digoburigo** [terrestris/ol-util#733]
Hello, i'm trying to run this lib with Angular. But i'm not being able to run it properly.

Error that occurs
```
core.mjs:6406 ERROR Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
    at 62271 (browser.js:2:16)
    at __webpack_require__ (bootstrap:19:1)
    at 31628 (browser.js:2:17)
    at __webpack_require__ (bootstrap:19:1)
    at 56586 (binaryajax-browser.js:2:17)
    at __webpack_require__ (bootstrap:19:1)
    at 74579 (binaryajax-fetch.js:2:18)
    at __webpack_require__ (bootstrap:19:1)
    at 78162 (index.js:7:20)
    at __webpack_require__ (bootstrap:19:1)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26510:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
```

To make it work I had to put this script in index.html
```html
<script>
    if (global === undefined) {
      var global = window;
    }
  </script>
```
There is some other way to make it work without this workaround?

**Comment by dnlkoch** [comment]
Hi @digoburigo,

this lib is not dependent on any particular frontend framework and should work with angular just fine. 

According to the log output it looks like you're making use of `webpack` to start your application and there may be an issue in its configuration causing the error. To replace the workaround in the `index.html` you might want to check the following:

- Provide [a polyfill](https://webpack.js.org/configuration/node/#nodeglobal) for `global`.
- Set the [target](https://webpack.js.org/configuration/target/) to `web`.
